language: node_js
node_js:
- '8'
before_install:
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn=1.19.2-1
cache:
  yarn: true
script:
- yarn install
- npm test
- npm run report-coverage
after_success:
- cat ./coverage/coverage-final.json | ./node_modules/codecov.io/bin/codecov.io.js