language: node_js
node_js:
- '8'
before_install:
  # Yarn
  - sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
cache:
  directories:
  - $HOME/.yarn-cache
script:
- yarn install
- npm test
- npm run report-coverage
after_success:
- cat ./coverage/coverage-final.json | ./node_modules/codecov.io/bin/codecov.io.js